# Example/Documentation for the IG YML file
# https://fshschool.org/docs/sushi/configuration/#exhaustive-example

# Package name
# https://confluence.hl7.org/display/FHIR/NPM+Package+Specification#NPMPackageSpecification-Packagename
id: ch.fhir.ig.ch-umzh-connect
canonical: http://fhir.ch/ig/ch-umzh-connect
name: CHUMZHConnect
title: "CH UMZH Connect IG (R4)"
description: FHIR Implementation Guide for the University Medicine Zurich (UMZH) focusing on referral processes
status: draft # draft | active | retired | unknown
license: CC0-1.0
copyright: CC0-1.0
jurisdiction: urn:iso:std:iso:3166#CHE
date: 2025-12-10
version: 1.0.0-cibuild # 1.2.2 published in May 2025
fhirVersion: 4.0.1
copyrightYear: 2024+
releaseLabel: ci-build # ci-build | draft | qa-preview | ballot | trial-use | release | update | normative+trial-use
publisher:
  name: UMZH
contact:
  - name: UMZH
    telecom:
      - system: url
        value: https://umzh.uzh.ch/

dependencies:
  ch.fhir.ig.ch-core: 6.0.0 # https://fhir.ch/ig/ch-core/index.html
  ch.fhir.ig.ch-emed: 6.0.0 # https://fhir.ch/ig/ch-emed/index.html
  ch.fhir.ig.ch-etoc: 3.0.1 # https://fhir.ch/ig/ch-etoc/index.html
  ch.fhir.ig.ch-orf: 3.0.2 # https://fhir.ch/ig/ch-orf/index.html
  hl7.fhir.uv.cow: 1.0.0-ballot 
pages:
  index.md:
    title: Home
  guidance-solution-concept.md:
    title: Guidance - Solution Concept
  guidance-security-concept.md:
    title: Guidance - Security Concept
  usecase-referral-orthopedic.md:
    title: Referral - Orthopedic Surgery
  usecase-referral-sarcoma-tumorboard.md:
    title: Referral - Sarcoma Tumor Board
  security.md:
    title: Security
  profiles.md:
    title: Profiles
  extensions.md:
    title: Extensions
  terminology.md:
    title: Terminology
  changelog.md:
    title: Changelog

menu:
  Home: index.html
  Use Cases:
    Referral - Orthopedic Surgery: usecase-referral-orthopedic.html
    Referral - Sarcoma Tumor Board: usecase-referral-sarcoma-tumorboard.html
  Guidance:
    Guidance - Solution Concept: guidance-solution-concept.html
    Guidance - Security Concept: guidance-security-concept.html
  Security: security.html
  Profiles: profiles.html
  Extensions: extensions.html
  Terminology: terminology.html
  Artifacts: artifacts.html


# Parameters
  # Core FHIR: http://build.fhir.org/codesystem-guide-parameter-code.html
  # FHIR Tools IG: http://build.fhir.org/ig/FHIR/fhir-tools-ig/branches/master/CodeSystem-ig-parameters.html
parameters:
  excludettl: true
  allow-extensible-warnings: true
  display-warnings: true 
  path-expansion-params: '../../expansion-params.json'  # for using SNOMED CT Swiss Extension
  pin-canonicals: pin-multiples
  path-resource:
    - input/resources  

FSHOnly: false
applyExtensionMetadataToRoot: false
instanceOptions:
  setMetaProfile: always
  setId: always
  manualSliceOrdering: true
